<template>
  <q-page class="q-pa-lg text-justify fondo-letra">
    <div class="text-subtitle2">Hacer una reseña histórica del Colegio Alemán, es tocar las fibras más íntimas de la educación de Oruro y de Bolivia, pues por sus aulas pasaron inmensa cantidad de estudiantes que hoy brillan en el campo intelectual, técnico y trabajan por el progreso de nuestra patria.</div>
<br>
    <div class="text-subtitle2">El auge minero trajo consigo migración extranjera que tuvo que asentarse en nuestra ciudad constituyéndose en un principio en colonias cerradas. Estas tuvieron varias necesidades entre ellas la educativa bajo la línea pedagógica y la disciplina alemana.</div>
<br>
    <div class="text-subtitle2">El 23 de febrero de 1922 fue invitada la colonia alemana en Oruro, dirigida por los señores: Erich Findel y el Dr. Fritz Mumme para intercambiar opiniones sobre la fundación de un colegio alemán en la ciudad sobre la necesidad de sustentar, fomentar y expandir el idioma alemán, las costumbres y tradiciones después de la espantosa guerra mundial.</div>
<br>
    <div class="text-subtitle2">En la ciudad de La Paz fue fundada una Asociación escolar, decidiendo incorporar al Grupo de residentes alemanes de Oruro. Con entusiasmo y alegría, se trabajó en la fundación y así proveerse de muebles, material escolar, local y profesores para el principio de la gestión escolar de la gestión 1923: "para el primer año recibir solamente niños de padres alemanes o aquellos cuyo padre es alemán". Se crea el "Centro Escolar Alemán", tratando de emular la calidad y los cánones de enseñanzas alemanes.</div>
<br>
    <div class="text-subtitle2">Al encontrar distintas ópticas con el grupo de La Paz, al año siguiente Oruro ejerce autonomía en su funcionamiento con ayuda de la colonia alemana; el centro educativo se ubicaba en la calle Grecia (Calle Sucre). Después de unos años ante el crecimiento del alumnado. La dirección del colegio solicitó la cooperación de "Las hermanas de las Escuelas Cristianas de la Compasión", quienes conformaron un internado para los estudiantes del colegio.</div>
<br>
    <div class="text-subtitle2">El año 1932 fue un año muy duro en cuanto a la manutención del colegio, pero con esfuerzos de la colonia alemana y maestros se pudo salir adelante. Un hito que marca este año es la incorporación en los registros no solo de estudiantes alemanes sino también bolivianos; asimismo, el colegio "Alemán" empieza a generar aceptación, trascendencia y prestigio en la sociedad orureña bajo la dirección del señor alemán Werner Golde.</div>
<br>
    <div class="text-subtitle2">La inauguración del edificio de la calle Sucre se da el año 1938 gracias a los aportes de la colonia alemana y el gobierno del Tercer Reich. Lamentablemente los acontecimientos de la Segunda Guerra Mundial dieron lugar a una interrupción educacional, siendo todos los residentes alemanes incluidos los profesores, deportados a los Estados Unidos. En esta época, se cambia el nombre del colegio y toma la denominación; por "Colegio Oruro". Siendo el profesor Alfredo Pereira el director y constituyéndose como el primer director Boliviano del colegio.</div>
<br>
    <div class="text-subtitle2">Después de la guerra, la República Federal de Alemania, envía a nuestro país a los señores alemanes, Gunter Walter y Hans Gerschutz, quienes tomaron la dirección del colegio, dando comienzo a una nueva etapa; en la cual, se renueva el aspecto técnico pedagógico, y se empieza a dotar al colegio de una infraestructura adecuada y un moderno material didáctico, el idioma alemán es intensificado como una materia de enseñanza, consecuentemente se da la llegada de docentes alemanes como apoyo para el colegio. Se crece en número de estudiantes y la calidad de educación es de alto nivel académico y pedagógico.</div>
<br>
    <div class="text-subtitle2">El colegio había tomado una modalidad experimental en 1962, pues se contaba con una subvención alemana, cabe mencionar que la mayoría de estudiantes eran bolivianos. Bajo la dirección del Sr. Sweickert; los resultados fueron óptimos, pues se había respondido a las expectativas formadas por el elemento estudiantil, quienes lograban a su vez una formación a un nivel profesional, sin mayores problemas ya sea fuera o dentro del país.</div>
<br>
    <div class="text-subtitle2">A inicios de la década del 70, el Sr. Hans Dieter Vogt, toma la dirección del colegio, quien, caracterizado por su dinamismo, permite que los mejores estudiantes de los colegios de Oruro que desearían estudiar en el colegio alemán obtén a una beca y, se logra el primer curso de becados, quienes se adaptaron sin problemas a la hermenéutica de la institución y lograron su bachillerato sin inconvenientes.</div>
<br>
    <div class="text-subtitle2">Un episodio muy trascendental que marcó el camino para la consolidación como una institución con visión de futuro fue el año 1975, cuando el Gobierno de Alemania mediante su embajada anuncia el cierre de varios colegios alemanes en Latino América y entre ellos los colegios Alemanes de Oruro y Sucre; es ahí, que el tezón y la determinación de los padres de familia a la cabeza de la Sra. María Galoppo de Araujo, Presidente de los padres de familia, organizo una movilización entre padres, docentes con la cooperación del "Centro Escolar alemán" para evitar el cierre del colegio; ya que la intención de los personeros encargados del cierre era entregar el colegio al gobierno o alguna institución religiosa. Fue una comisión de padres de familia el director y varios profesores quienes se presentaron en el Ministerio de Educación para defender el funcionamiento del colegio y expusieron sus razones para mantener el colegio y su nombre vigente.</div>
<br>
    <div class="text-subtitle2">Después de arduas negociaciones los delegados de la embajada dieron el tiempo de dos años como prueba para ver si la administración boliviana podía sostener el colegio. De esta manera es que el Centro Escolar, junto con el Comité Administrativo se hicieron cargo del manejo económico, manejo humano, material para encarar el funcionamiento del colegio. Bajo la dirección del Prof. Juan Molina Rodríguez; se priorizó, un modelo de enseñanza basado en la disciplina, el orden, el respeto, una educación en valores, fomento al desarrollo de las ciencias, el deporte, la cultura en el ámbito académico y humano.</div>
<br>
    <div class="text-subtitle2">A fines del siglo XX y principios del siglo XXI, el Colegio "Alemán", se constituye en un colegio modelo siendo uno de los mejores de Oruro, por los logros cosechados, enseñanza de calidad, docentes calificados al servicio de la educación con alto grado de compromiso, trabajo y esmero. El colegio, a la cabeza del Lic. Flavio Lagrava Rodríguez como Director, ha logrado mantenerse, destacarse y marcar la diferencia en las ferias de ciencias, olimpiadas departamentales, nacionales, internacionales, presencia en eventos académicos y científicos. En el ámbito deportivo se han conseguido incontables triunfos, trofeos, plaquetas, galardones, distinciones y siempre ha dado a nuestra tierra los mejores deportistas. Eventos que tienen que ver con la cultura, la formación de líderes, la investigación, la exploración científica, la producción de textos, la promoción de la lectura, el arte literario en niños y jóvenes; representando a nuestro distrito y nuestro país en varios eventos llevando en alto grado el nombre de Oruro y de Bolivia.</div>
<br>
    <div class="text-subtitle2">Las metas y los desafíos continúan, a vísperas de llegar al Centenario de su fundación, el horizonte es amplio, las sociedades se han transformado y el avance tecnológico está presente en sus aulas, obligando a asumir un nuevo enfoque y una visión futurista, orientada a la superación para seguir un nuevo rumbo educativo que nos permita mantener el sitial privilegiado y muy bien ganado en Bolivia.</div>
<br>
    "Rompe el himno triunfal de la alborada, resuena brillante mi canción en el nombre de Dios y de la patria a luchar con la fe y el corazón...”
  </q-page>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'HistoriaPage'
})
</script>
