<template>
  <q-page class="q-pa-lg text-justify">
    <div class="text-subtitle2"><span class="text-bold">1.  Respeto.-</span> El respeto es uno de los valores morales más importantes del ser humano, pues es fundamental para lograr una armoniosa interacción social. El respeto debe ser mutuo y nacer de un sentimiento de reciprocidad. El respeto también debe aprenderse. Respetar trata de no discriminar ni ofender a esa persona por su forma de vida y sus decisiones, siempre y cuando dichas decisiones no causen ningún daño, ni afecten o irrespeten a los demás.</div><br>
    <div class="text-subtitle2">Todo debe basarse en el respeto, el respeto es un componente muy importante tanto de la identidad personal como de las relaciones interpersonales. El respeto es un valor que permite que el hombre pueda reconocer, aceptar, apreciar y valorar las cualidades del prójimo y sus derechos. Es decir, el respeto es el reconocimiento del valor propio y de los derechos de los individuos y de la sociedad.</div><br>
    <div class="text-subtitle2"><span class="text-bold">2.  Disciplina.-</span> Se valora la disciplina, entendida como un rasgo positivo del individuo, cuando se traduce en la capacidad para seguir instrucciones, para obedecer a un sistema lógico y positivo de hacer las cosas, o incluso cuando un individuo es capaz de imponerse a sí mismo un método y seguirlo al pie de la letra (autodisciplina). Este término se define como la capacidad que tienen las personas para llevar a cabo un conjunto de principios que se relacionan con la constancia y el orden, esto lo hacen en la ejecución de actividades diarias como de las tareas comunes, es decir, en la vida general. Empleada para que los alumnos aprendan a relacionarse tanto con sus iguales como con sus superiores. También funciona para que los alumnos cumplan con los deberes, aprendan a seguir las normas y los códigos de conducta de la institución, de manera que se pueda asegurar la correcta convivencia dentro del plantel.</div><br>
    <div class="text-subtitle2"><span class="text-bold">3.  Orden.-</span> El orden es un valor que se aprende en el hogar y que nos acompañará toda la vida. Hay personas que son ordenadas por naturaleza y otras que deben adquirir este valor.  Cualquiera que sea el caso, el orden es indispensable para triunfar en la vida y en ello radica la importancia de inculcarlo en los estudiantes desde muy pequeños. Según David Isaac, una persona virtuosa en el orden “Se comporta de acuerdo a unas normas lógicas, necesarias para el logro de algún objetivo deseado y previsto, en la organización de las cosas, en la distribución del tiempo y en la realización de las actividades, por iniciativa propia, sin que sea necesario recordárselo” (Isaac, 1986). Su importancia radica en que nos permite ser responsables, eficientes, productivos y organizados. Adicionalmente nos proporciona calma, serenidad, confianza y nos ayuda a ser más felices con menos esfuerzo (Alcázar, 2001). El orden es un valor que se evidencia en el trabajo, en los estudios, así como en todas las actividades del día a día</div><br>
    <div class="text-subtitle2"><span class="text-bold">4.  Puntualidad.-</span> Llegar al colegio con puntualidad y bien preparados ayuda a los estudiantes a tener éxito en los estudios. Los estudiantes que llegan a tiempo a la escuela, sin nervios, bien desayunados, que llevan los útiles escolares que van a necesitar y los trabajos hechos tienen más seguridad en sí mismos y asisten más contentos a las clases. La puntualidad en el colegio es una actitud que se adquiere desde los primeros años de vida mediante la formación de hábitos en la familia. También es un reflejo de respeto al tiempo de los demás. La puntualidad en la escuela es un signo de buena educación. Sin embargo, en algunos casos hay personas que constantemente llegan tarde y, generalmente presentan excusas, por ejemplo, no sonó el despertador, mi mamá me retrasó, no pasó a tiempo el transporte, etc., y esto ocasiona un retraso para todos. La llegada a tiempo al colegio depende por partes iguales de los estudiantes, y del conjunto de la familia. Por supuesto, es la familia quien educa a sus hijos para que colaboren y adquieran la responsabilidad necesaria para llegar a tiempo.</div><br>
    <div class="text-subtitle2"><span class="text-bold">5.  Solidaridad.-</span> Ser solidario tiene muchos beneficios para las personas, no solo para el que recibe la ayuda, sino también para el que la presta. Ayudar sin esperar nada a cambio, es un valor humano y por lo tanto se convierte en una actitud, en una manera de actuar. Ser solidarios en la escuela quiere ofreceros algunos de los recursos que hay relacionados. Uno de los valores humanos más importantes es la Solidaridad, que consiste en brindar la ayuda a otro que la necesita. Es un sentimiento de unidad que se basa en metas o intereses comunes. Hace referencia a la capacidad y la voluntad de algunas personas de ayudar a otros sin recibir nada a cambio. De compartir hogar, alimentos, sentimientos, etc. con otro ser vivo sin tener en cuenta su situación económica.</div><br>
  </q-page>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'ValoresPage'
})
</script>
